spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products_database
    username: user
    password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/products_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

redis:
  host: localhost
  port: 6379
  timeout: 6000ms